name: csv_sheet
version: 0.0.2+3
author: Matthew Butler <butler.matthew@gmail.com>
description: Library for dealing with CSV Spreadsheets.
homepage: https://github.com/butlermatt/csv_sheet
environment:
  sdk: '>=1.3.0 <1.7.0'
documentation: http://www.dartdocs.org/documentation/csv_sheet/0.0.2+3/
dev_dependencies:
  unittest: '>=0.11.0 <0.12.0'
